name: 'adventure_works_dbt'
version: '1.0.0'
config-version: 2

profile: 'adventure_works'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  adventure_works_dbt:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

vars:
  # Add any project variables here
  project_start_date: '2011-01-01'
  project_end_date: '2014-12-31'

seeds:
  adventure_works_dbt:
    +column_types:
      id: integer
      created_at: timestamp
      updated_at: timestamp

# Source definitions
sources:
  - name: erp
    description: "Adventure Works ERP system data (SAP)"
    tables:
      - name: salesorderheader
        description: "Sales order header information"
        columns:
          - name: salesorderid
            description: "Primary key for sales order"
            tests:
              - unique
              - not_null
          - name: orderdate
            description: "Date when order was placed"
            tests:
              - not_null
          - name: customerid
            description: "Foreign key to customer"
            tests:
              - not_null
          - name: salespersonid
            description: "Foreign key to salesperson"
          - name: billtoaddressid
            description: "Billing address ID"
          - name: shiptoaddressid
            description: "Shipping address ID"
      
      - name: salesorderdetail
        description: "Sales order line items"
        columns:
          - name: salesorderid
            description: "Foreign key to sales order header"
            tests:
              - not_null
          - name: salesorderdetailid
            description: "Primary key for order detail"
            tests:
              - unique
              - not_null
          - name: productid
            description: "Foreign key to product"
            tests:
              - not_null
          - name: orderqty
            description: "Quantity ordered"
            tests:
              - not_null
          - name: unitprice
            description: "Unit price"
            tests:
              - not_null
          - name: discount
            description: "Discount percentage"
      
      - name: salesreason
        description: "Sales reason codes"
        columns:
          - name: salesreasonid
            description: "Primary key for sales reason"
            tests:
              - unique
              - not_null
          - name: name
            description: "Name of the sales reason"
            tests:
              - not_null
          - name: reasontype
            description: "Type of sales reason"
      
      - name: person
        description: "Person information (customers and employees)"
        columns:
          - name: businessentityid
            description: "Primary key for person"
            tests:
              - unique
              - not_null
          - name: persontype
            description: "Type of person (EM, SP, SC, VC, IN, GC)"
            tests:
              - not_null
          - name: firstname
            description: "First name"
            tests:
              - not_null
          - name: lastname
            description: "Last name"
            tests:
              - not_null
          - name: emailpromotion
            description: "Email promotion preference"
      
      - name: product
        description: "Product catalog information"
        columns:
          - name: productid
            description: "Primary key for product"
            tests:
              - unique
              - not_null
          - name: name
            description: "Product name"
            tests:
              - not_null
          - name: productnumber
            description: "Product number"
            tests:
              - not_null
          - name: color
            description: "Product color"
          - name: size
            description: "Product size"
          - name: weight
            description: "Product weight"
      
      - name: address
        description: "Address information"
        columns:
          - name: addressid
            description: "Primary key for address"
            tests:
              - unique
              - not_null
          - name: addressline1
            description: "First address line"
            tests:
              - not_null
          - name: addressline2
            description: "Second address line"
          - name: city
            description: "City name"
            tests:
              - not_null
          - name: postalcode
            description: "Postal code"
          - name: spatiallocation
            description: "Spatial location data"
      
      - name: stateprovince
        description: "State and province information"
        columns:
          - name: stateprovinceid
            description: "Primary key for state/province"
            tests:
              - unique
              - not_null
          - name: name
            description: "State/province name"
            tests:
              - not_null
          - name: countryregioncode
            description: "Country region code"
            tests:
              - not_null
      
      - name: countryregion
        description: "Country and region information"
        columns:
          - name: countryregioncode
            description: "Primary key for country/region"
            tests:
              - unique
              - not_null
          - name: name
            description: "Country/region name"
            tests:
              - not_null

  - name: crm
    description: "Adventure Works CRM system data (SalesForce)"
    tables:
      - name: customer
        description: "CRM customer information"
        columns:
          - name: customerid
            description: "Primary key for customer"
            tests:
              - unique
              - not_null

  - name: web_analytics
    description: "Adventure Works web analytics data (Google Analytics)"
    tables:
      - name: pageviews
        description: "Website page view data"
        columns:
          - name: sessionid
            description: "Session identifier"
            tests:
              - not_null

  - name: website
    description: "Adventure Works website data (WordPress)"
    tables:
      - name: posts
        description: "Website blog posts"
        columns:
          - name: postid
            description: "Primary key for post"
            tests:
              - unique
              - not_null
