name: 'adventure_works_dbt'
version: '1.0.0'
config-version: 2

profile: 'adventure_works'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  start_date: "2011-01-01"
  end_date: "2015-12-31"
  
models:
  adventure_works_dbt:
    +materialized: ephemeral    
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

